import type { Metadata } from "next";
import "./globals.css";
import '@fontsource/firago';
import Navigation from '@/components/header/Navigation'
export const metadata: Metadata = {
  title: "Ganivi Plan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-[8rem]">
      <Navigation />
        {children}
      </body>
    </html>
  );
}
